services:
  app:
    build: .
    image: hb-cli
    restart: unless-stopped
    env_file: .env
    init: true
    volumes:
      - ./hb-cli.db:/app/hb-cli.db
      - ./hb-cli.log:/app/hb-cli.log
    command: ["npm", "start"]
